
- block:
    - name: Check .netrc
      ansible.builtin.stat: path={{ user }}/.netrc
      register: netrc
    - ansible.builtin.debug:
        msg: 'WARN: netrc present'
      when: netrc.stat.exists
